---
- name: Setup and secure mariadb on ubuntu
  hosts: mariadb_servers
  become: true
  vars:
    mariadb_root_password: "root_Password"
    mariadb_database: "mariadb"
    mariadb_user: "my_user"
    mariadb_user_password: "user_password"

  tasks:
    - name: Update Apt package index
      apt: 
        update_cache: yes
    
    - name: Install Mariadb server and client
      apt:
        name: 
          - mariadb-server
          - mariadb-client
        state: present


    - name: Start and Enable Mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: wait for mariadb to start
      wait_for: 
        port: 3306
        delay: 10
        timeout: 300


    - name: Ensure Maridb is configured to allow root login
      lineinfile: 
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Restart Mariadb

    - name: Secure Mariadb installation
      expect:
        command: "mysql -u root"
        responses: 
          "Enter password for user root:": ""
          "Welcome to the MariaDB": ""
          "Would you like to setup a root password?": "Y"
          "New password:": "{{ mariadb_root_password }}"
          "Re-enter new password:": "{{ mariadb_root_password }}"
          "Remove anonymous users?": "Y"
          "Disallow root login remotely?": "Y"
          "Remove test database and access to it?": "Y"
          "Reload privilege tables now?": "Y"

    - name: Create database
      mysql_db:
        name: "{{ mariadb_database }}"
        state: present

    - name: Create user and grant privileges
      mysql_user:
        name: "{{ mariadb_user }}"
        password: "{{ mariadb_user_password }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present

    - name: Flush privileges
      mysql_privs:
        name: "{{ mariadb_user }}"
        priv: "{{ mariadb_database }}.*:ALL"
        state: present

  handlers:
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted


